In [1]:
import numpy as np

In [7]:
x=np.array(["vani",5,7.6,88,33])
print(x)
print(type(x))
print(x.dtype)

['vani' '5' '7.6' '88' '33']
<class 'numpy.ndarray'>
<U32


In [11]:
a=np.array([[10,30],[36,100]])
print(a)
print(type(a))
print(a.shape)

[[ 10  30]
 [ 36 100]]
<class 'numpy.ndarray'>
(2, 2)


In [27]:
a=np.array([10,23,55,33])
b=a.reshape(2,2)
print(b)
print(b.shape)


[[10 23]
 [55 33]]
(2, 2)


In [29]:
c=np.arange(3,15)
print(c)
type(c)


[ 3  4  5  6  7  8  9 10 11 12 13 14]


numpy.ndarray

In [31]:
d=np.array([1.3456473,9.8387364,7.65291])
d

array([1.3456473, 9.8387364, 7.65291  ])

In [33]:
print(np.around(np.sqrt(d),2))

[1.16 3.14 2.77]


In [39]:
t=np.array([[3,8,9,2],[9,7,8,np.NAN]])
print(t)

[[ 3.  8.  9.  2.]
 [ 9.  7.  8. nan]]


In [49]:
t1=np.array([[3,9,2],[9,7,8],[2,34,4]])
print(t1)
type(t1)

[[ 3  9  2]
 [ 9  7  8]
 [ 2 34  4]]


numpy.ndarray

In [45]:
tcopy=t.astype(str)
print(tcopy)

[['3.0' '8.0' '9.0' '2.0']
 ['9.0' '7.0' '8.0' 'nan']]


In [51]:
print(t1.sum(axis = 1))
print(t1.sum(axis = 0))

[14 24 40]
[14 50 14]


In [53]:
print(np.mean(t1,axis = 1))
print(np.mean(t1,axis = 0))

[ 4.66666667  8.         13.33333333]
[ 4.66666667 16.66666667  4.66666667]


In [59]:
t1=np.array([[3,9,2],[9,7,8],[2,34,4]])
print(t1)
np.fill_diagonal(t1,6)
print(t1)

[[ 3  9  2]
 [ 9  7  8]
 [ 2 34  4]]
[[ 6  9  2]
 [ 9  6  8]
 [ 2 34  6]]


In [65]:
V=np.array([[3,4],[2,3]])
M=np.array([[2,6],[9,5]])
c=np.matmul(V,M)
print(c)

[[42 38]
 [31 27]]


In [67]:
print(V.T)
print(M.T)

[[3 2]
 [4 3]]
[[2 9]
 [6 5]]


In [69]:
t1=np.array([[3,9,2],[9,7,8],[2,34,4],[3,4,6]])
print(t1)

[[ 3  9  2]
 [ 9  7  8]
 [ 2 34  4]
 [ 3  4  6]]


In [71]:
 t1[:,1:]

array([[ 9,  2],
       [ 7,  8],
       [34,  4],
       [ 4,  6]])

In [81]:
t1[1:3,0:2]

array([[ 9,  7],
       [ 2, 34]])